// Code generated by protoc-gen-go. DO NOT EDIT.
// source: items.proto

package items

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Images               []string `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8bad7296e45e12f, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

type Items struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8bad7296e45e12f, []int{1}
}
func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (m *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(m, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

func (m *Items) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ItemID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemID) Reset()         { *m = ItemID{} }
func (m *ItemID) String() string { return proto.CompactTextString(m) }
func (*ItemID) ProtoMessage()    {}
func (*ItemID) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8bad7296e45e12f, []int{2}
}
func (m *ItemID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemID.Unmarshal(m, b)
}
func (m *ItemID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemID.Marshal(b, m, deterministic)
}
func (m *ItemID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemID.Merge(m, src)
}
func (m *ItemID) XXX_Size() int {
	return xxx_messageInfo_ItemID.Size(m)
}
func (m *ItemID) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemID.DiscardUnknown(m)
}

var xxx_messageInfo_ItemID proto.InternalMessageInfo

func (m *ItemID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8bad7296e45e12f, []int{3}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Item)(nil), "items.Item")
	proto.RegisterType((*Items)(nil), "items.Items")
	proto.RegisterType((*ItemID)(nil), "items.ItemID")
	proto.RegisterType((*Void)(nil), "items.Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Items, error)
	ItemInfo(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*Item, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Items, error) {
	out := new(Items)
	err := c.cc.Invoke(ctx, "/items.ItemService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemInfo(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/items.ItemService/ItemInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	List(context.Context, *Void) (*Items, error)
	ItemInfo(context.Context, *ItemID) (*Item, error)
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/items.ItemService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).List(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/items.ItemService/ItemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemInfo(ctx, req.(*ItemID))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "items.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ItemService_List_Handler,
		},
		{
			MethodName: "ItemInfo",
			Handler:    _ItemService_ItemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "items.proto",
}

func init() { proto.RegisterFile("items.proto", fileDescriptor_f8bad7296e45e12f) }

var fileDescriptor_f8bad7296e45e12f = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0x2f, 0xbb, 0xd9, 0xc5, 0x9b, 0xa8, 0xc5, 0x20, 0x12, 0xae, 0x8a, 0xb1, 0x09, 0x16,
	0x57, 0x9c, 0xaf, 0x70, 0xcd, 0x82, 0x55, 0x04, 0x2b, 0x9b, 0xf3, 0x36, 0xca, 0x14, 0xbb, 0x59,
	0x92, 0x60, 0xe1, 0xd3, 0x4b, 0xb2, 0x27, 0x04, 0xbb, 0x7c, 0xf9, 0x87, 0x7f, 0x3e, 0x06, 0x04,
	0x25, 0x37, 0xc5, 0xfd, 0x12, 0x7c, 0xf2, 0xd8, 0x15, 0xd0, 0x3f, 0xc0, 0x87, 0xe4, 0x26, 0xbc,
	0x85, 0x86, 0x46, 0xc9, 0x14, 0x33, 0xad, 0x6d, 0x68, 0x44, 0x04, 0x3e, 0x9f, 0x26, 0x27, 0x1b,
	0xc5, 0xcc, 0xd6, 0x96, 0x37, 0x2a, 0x10, 0xa3, 0x8b, 0xe7, 0x40, 0x4b, 0x22, 0x3f, 0xcb, 0xb6,
	0x44, 0xf5, 0x17, 0xde, 0x41, 0xb7, 0x04, 0x3a, 0x3b, 0xc9, 0x15, 0x33, 0xcc, 0xae, 0x80, 0xf7,
	0xd0, 0xd3, 0x74, 0xfa, 0x72, 0x51, 0x76, 0xaa, 0x35, 0x5b, 0x7b, 0x21, 0xfd, 0x04, 0x5d, 0xde,
	0x1d, 0xf1, 0x01, 0x56, 0x1b, 0xc9, 0x54, 0x6b, 0xc4, 0x41, 0xec, 0x57, 0xd1, 0x1c, 0xda, 0x8b,
	0xa7, 0x84, 0x3e, 0xe3, 0x70, 0xfc, 0x6f, 0xaa, 0x7b, 0xe0, 0x6f, 0x9e, 0xc6, 0xc3, 0x3b, 0x88,
	0x3c, 0xf1, 0xea, 0xc2, 0x77, 0x5e, 0xfa, 0x08, 0xfc, 0x85, 0x62, 0xc2, 0xbf, 0xb2, 0x3c, 0xb3,
	0xbb, 0xae, 0x9a, 0xa3, 0xde, 0xa0, 0x81, 0xab, 0xd2, 0x3a, 0x7f, 0x7a, 0xbc, 0xa9, 0xb2, 0xe1,
	0xb8, 0xab, 0x25, 0xf4, 0xe6, 0xa3, 0x2f, 0x57, 0x7b, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x98,
	0x2b, 0x1e, 0xf6, 0x44, 0x01, 0x00, 0x00,
}
